[project]
name = "indirect_GWAS"
version = "0.0.1"
dependencies = ["numpy", "pandas", "scipy", "xarray"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
indirect-GWAS = "indirect_GWAS.cli:main"
compute-feature-partial-covariance = "indirect_GWAS.cli:compute_feature_partial_covariance"
